apiVersion: v1
kind: Service
metadata:
  name: reddit-clone-service
spec:
  selector:
    app: reddit-clone
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30009
  type: NodePort
